[tool.poetry]
name = "rideshare"
version = "1.0.0"
description = ""
authors = ["Your Name"]

[tool.poetry.dependencies]
python = "^3.11"
Flask = "3.0.3"
gunicorn = "23.0.0"
requests = "2.31.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
